# Generated by Django 3.2.5 on 2021-11-28 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_subject', models.CharField(max_length=255)),
                ('post_contents', models.TextField()),
                ('post_category', models.CharField(max_length=255, null=True)),
                ('post_tags', models.CharField(max_length=255, null=True)),
                ('post_sector', models.CharField(max_length=255)),
                ('post_year', models.CharField(max_length=255)),
                ('report_code', models.CharField(max_length=10)),
                ('is_success', models.BooleanField(default=False)),
                ('post_url', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(null=True)),
            ],
        ),
    ]
